EXTERNAL ChangeScene(sceneType)
EXTERNAL FadeBackground(fileName, duration)
EXTERNAL PanBackground(fileName, duration)
EXTERNAL Delay(duration)
EXTERNAL PlayAudio(fileName)
EXTERNAL LoopAudio(fileName)
EXTERNAL PlayAudioWithDuration(fileName, duration)
EXTERNAL SetAudioVolume(fileName, volume)
EXTERNAL FadeAudioVolume(fileName, volume, duration)
EXTERNAL StopAudio(fileName)
EXTERNAL SetRhythmGameSong(songName)
